# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-cplusplus
  include:
    - dobi.yaml
    - version.yaml
    - service/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - bb-cplusplus-version
  annotations:
    description: "[alias] bb-cplusplus-version"

alias=build:
  tasks:
    - bb-cplusplus-build
  annotations:
    description: "[alias] bb-cplusplus-build"

alias=analyze:
  tasks:
    - bb-cplusplus-analyze
  annotations:
    description: "[alias] bb-cplusplus-analyze"

alias=test:
  tasks:
    - bb-cplusplus-test
  annotations:
    description: "[alias] bb-cplusplus-test"

alias=doxygen:
  tasks:
    - bb-cplusplus-doxygen
  annotations:
    description: "[alias] bb-cplusplus-doxygen"

alias=debug:
  tasks:
    - bb-cplusplus-debug
  annotations:
    description: "[alias] bb-cplusplus-debug"