# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-cplusplus
  include:
    - dobi.yaml
    - version.yaml
    - cplusplus/dobi.yaml
    - example/cplusplus/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - bb-cplusplus-version
  annotations:
    description: "[alias] bb-cplusplus-version"

alias=build:
  tasks:
    - bb-cplusplus-build
  annotations:
    description: "[alias] bb-cplusplus-build"

alias=deploy:
  tasks:
    - bb-cplusplus-deploy
  annotations:
    description: "[alias] bb-cplusplus-deploy"

alias=test:
  tasks:
    - bb-cplusplus-test
  annotations:
    description: "[alias] bb-cplusplus-test"
