resources:
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((privatekey))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: ((bb_gitversion_version))

  - name: s3-gitversion
    type: s3
    source:
      bucket: ((bb_name))
      endpoint: ((s3_endpoint))
      regexp: gitversion/gitversion-(.*).tar.gz
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      disable_ssl: ((s3_skip_ssl_verification))

  - name: image-aws-cli
    type: docker-image
    source:
      repository: amazon/aws-cli
      tag: 2.0.22

  - name: image-((bb_name))-builder
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-builder
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
      tag: ((bb_builder_version))

  - name: image-((bb_name))-runtime-x86_64
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-runtime-x86_64
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
      tag: ((bb_runtime_version))

jobs:
  - name: Generate gitversion and put it on S3
    public: true
    plan:
      - in_parallel:
          - get: image-bb-gitversion-tool
          - get: source
            trigger: true
          - get: image-aws-cli
      - task: Generate version
        image: image-bb-gitversion-tool
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gitversion
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh &&
                jq empty gitversion/json/gitversion.json &&
                cat gitversion/json/gitversion.json &&
                tar cvfz gitversion/gitversion-$(cat gitversion/plain/BranchVersion).tar.gz gitversion/*
          params:
            GIT_PATH: source
            GEN_PATH: gitversion
      - task: Check/Create bucket for ((bb_name)) on S3
        image: image-aws-cli
        config:
          platform: linux
          run:
            path: /bin/bash
            args:
              - -xc
              - |
                mkdir -p ~/.aws
                # hide setting credentials in plain text in concourse ui
                set +x
                export TERM="xterm-256color"
                echo "[default]" > ~/.aws/credentials
                echo "aws_access_key_id=((s3_access_key))" >> ~/.aws/credentials
                echo "aws_secret_access_key=((s3_secret_key))" >> ~/.aws/credentials
                set -x
                # check if bucket exists on s3 endpoint. If not create one
                aws --endpoint-url ((s3_endpoint)) s3api head-bucket --bucket ((bb_name)) 2> /dev/null
                if [ $? != 0 ]; then aws s3 mb s3://((bb_name)) --endpoint-url ((s3_endpoint)); fi
      - put: s3-gitversion
        params:
          file: gitversion/gitversion-*.tar.gz
          acl: public-read

  - name: Build cplusplus_service
    public: true
    plan:
      - in_parallel:
          - get: image-((bb_name))-builder
          - get: image-((bb_name))-runtime-x86_64
          - get: source
          - get: s3-gitversion
            passed: [Generate gitversion and put it on S3]
            trigger: true
            params:
              unpack: true
      - in_parallel:
        - task: Build cplusplus_service x86_64
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
              - name: s3-gitversion
            outputs:
              - name: install-((bb_name))-x86_64
              - name: analyze
              - name: build
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  chmod a+w . && chmod a+w analyze && chmod a+w build && chmod a+w ${INSTALL_DIR};
                  /usr/local/bin/entrypoint.sh source/service/service.build.sh \
                  && cp ${BUILD_DIR}/compile_commands.json ./analyze/
            params:
              ARCH: "x86_64"
              BB_GITVERSION_INCLUDE_DIR: "s3-gitversion/gitversion/cpp"
              BUILD_DIR: "build"
              CMAKE_BUILD_TYPE: "Release"
              CONAN_LOGIN_USERNAME: "((conan_user))"
              CONAN_PASSWORD: "((conan_password))"
              CONAN_REMOTE: "((conan_remote))"
              CONAN_USER_HOME: "build"
              CONAN_SSL_VERIFICATION: "((conan_ssl_verification))"
              INSTALL_DIR: "install-((bb_name))-x86_64"
              SOURCE_DIR: "source/service"

        - task: Build cplusplus_service aarch64
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
              - name: s3-gitversion
            outputs:
              - name: install-((bb_name))-aarch64
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  chmod a+w . && chmod a+w ${INSTALL_DIR};
                  /usr/local/bin/entrypoint.sh source/service/service.build.sh
            params:
              ARCH: "aarch64"
              BB_GITVERSION_INCLUDE_DIR: "s3-gitversion/gitversion/cpp"
              BUILD_DIR: "build"
              CMAKE_BUILD_TYPE: "Release"
              CONAN_LOGIN_USERNAME: "((conan_user))"
              CONAN_PASSWORD: "((conan_password))"
              CONAN_REMOTE: "((conan_remote))"
              CONAN_USER_HOME: "build"
              CONAN_SSL_VERIFICATION: "((conan_ssl_verification))"
              INSTALL_DIR: "install-((bb_name))-aarch64"
              SOURCE_DIR: "source/service"

        - task: Build cplusplus_service armv7hf
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
              - name: s3-gitversion
            outputs:
              - name: install-((bb_name))-armv7hf
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  chmod a+w . && chmod a+w ${INSTALL_DIR};
                  /usr/local/bin/entrypoint.sh source/service/service.build.sh
            params:
              ARCH: "armv7hf"
              BB_GITVERSION_INCLUDE_DIR: "s3-gitversion/gitversion/cpp"
              BUILD_DIR: "build"
              CMAKE_BUILD_TYPE: "Release"
              CONAN_LOGIN_USERNAME: "((conan_user))"
              CONAN_PASSWORD: "((conan_password))"
              CONAN_REMOTE: "((conan_remote))"
              CONAN_USER_HOME: "build"
              CONAN_SSL_VERIFICATION: "((conan_ssl_verification))"
              INSTALL_DIR: "install-((bb_name))-armv7hf"
              SOURCE_DIR: "source/service"

      - in_parallel:
        - task: unittest
          image: image-((bb_name))-runtime-x86_64
          config:
            platform: linux
            inputs:
              - name: install-((bb_name))-x86_64
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  env;
                  cd install-${BB_NAME}-x86_64 \
                  && ./cplusplus_service_unit_test
            params:
              BB_NAME: "((bb_name))"

        - task: analyze
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: analyze
              - name: build
              - name: source
              - name: s3-gitversion
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  sed -i "s@/tmp/build/[^/]*/@$(pwd)/@g" analyze/compile_commands.json
                  cd analyze \
                  && CodeChecker analyze compile_commands.json -o reports/ \
                  && CodeChecker store reports/ --name "${BB_NAME}" --url ${CODECHECKER_URL}
            params:
              BB_NAME: ((bb_name))
              CODECHECKER_URL: ((codechecker_url))

        - task: doxygen
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  mkdir source/build; \
                  cd source/service/doxygen; \
                  doxygen Doxyfile;
