resources:
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((privatekey))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: ((bb_gitversion_version))

  - name: s3-gitversion
    type: s3
    source:
      bucket: ((bb_name))
      endpoint: ((s3_endpoint))
      regexp: gitversion/gitversion-(.*).tar.gz
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      disable_ssl: ((s3_skip_ssl_verification))

  - name: image-aws-cli
    type: docker-image
    source:
      repository: amazon/aws-cli
      tag: 2.0.22

  - name: image-((bb_name))-builder
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-builder
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))

  - name: image-((bb_name))-runtime-x86_64
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-runtime-x86_64
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_name))-runtime-x86_64-dev
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-runtime-x86_64-dev
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_name))-runtime-aarch64
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-runtime-aarch64
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_name))-runtime-aarch64-dev
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_name))-runtime-aarch64-dev
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))

jobs:
  - name: Generate gitversion and put it on S3
    public: true
    plan:
      - in_parallel:
          - get: image-bb-gitversion-tool
          - get: source
            trigger: true
          - get: image-aws-cli
      - task: Generate version
        image: image-bb-gitversion-tool
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gitversion
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh &&
                jq empty gitversion/json/gitversion.json &&
                cat gitversion/json/gitversion.json &&
                tar cvfz gitversion/gitversion-$(cat gitversion/plain/BranchVersion).tar.gz gitversion/*
          params:
            GIT_PATH: source
            GEN_PATH: gitversion
      - task: Check/Create bucket for ((bb_name)) on S3
        image: image-aws-cli
        config:
          platform: linux
          run:
            path: /bin/bash
            args:
              - -xc
              - |
                mkdir -p ~/.aws
                # hide setting credentials in plain text in concourse ui
                set +x
                export TERM="xterm-256color"
                echo "[default]" > ~/.aws/credentials
                echo "aws_access_key_id=((s3_access_key))" >> ~/.aws/credentials
                echo "aws_secret_access_key=((s3_secret_key))" >> ~/.aws/credentials
                set -x
                # check if bucket exists on s3 endpoint. If not create one
                aws --endpoint-url ((s3_endpoint)) s3api head-bucket --bucket ((bb_name)) 2> /dev/null
                if [ $? != 0 ]; then aws s3 mb s3://((bb_name)) --endpoint-url ((s3_endpoint)); fi
      - put: s3-gitversion
        params:
          file: gitversion/gitversion-*.tar.gz
          acl: public-read

  - name: Create docker images for ((bb_name)) and push them
    public: true
    plan:
      - in_parallel:
          - get: source
          - get: s3-gitversion
            passed: [Generate gitversion and put it on S3]
            trigger: true
            params:
              unpack: true
      - in_parallel:
          - put: image-((bb_name))-builder
            params:
              build: source/builder
              dockerfile: source/builder/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: s3-gitversion/gitversion/plain/BranchVersion
          - put: image-((bb_name))-runtime-x86_64
            params:
              build: source/runtime
              build_args:
                ARCH: "amd64"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: s3-gitversion/gitversion/plain/BranchVersion
          - put: image-((bb_name))-runtime-x86_64-dev
            params:
              build: source/runtime
              build_args:
                ARCH: "amd64"
                DEV: "1"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: s3-gitversion/gitversion/plain/BranchVersion
          - put: image-((bb_name))-runtime-aarch64
            params:
              build: source/runtime
              build_args:
                ARCH: "arm64v8"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: s3-gitversion/gitversion/plain/BranchVersion
          - put: image-((bb_name))-runtime-aarch64-dev
            params:
              build: source/runtime
              build_args:
                ARCH: "arm64v8"
                DEV: "1"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: s3-gitversion/gitversion/plain/BranchVersion

  - name: Build cplusplus_service
    public: true
    plan:
      - in_parallel:
          - get: image-((bb_name))-builder
            passed: [Create docker images for ((bb_name)) and push them]
          - get: source
          - get: s3-gitversion
            passed: [Generate gitversion and put it on S3]
            trigger: true
            params:
              unpack: true
      - in_parallel:
        - task: Build cplusplus_service x86_64
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
              - name: s3-gitversion
            outputs:
              - name: install-((bb_name))-x86_64
              - name: analyze
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  export CONAN_CPU_COUNT=$(nproc --all)
                  mkdir build \
                  && cd build \
                  && conan install ../source/service --build missing \
                  && cmake ../source/service -DCMAKE_INSTALL_PREFIX=../install-${BB_NAME}-${ARCH} -DCMAKE_CXX_FLAGS=-I\ ../s3-gitversion/gitversion/cpp -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                  && make -j${CONAN_CPU_COUNT} install \
                  && cp
            params:
              BB_NAME: ((bb_name))
              ARCH: x86_64
              BUILD_TYPE: Release
        - task: Build cplusplus_service aarch64
          image: image-((bb_name))-builder
          config:
            platform: linux
            inputs:
              - name: source
              - name: s3-gitversion
            outputs:
              - name: install-((bb_name))-aarch64
            run:
              path: /bin/bash
              args:
                - -exc
                - |
                  export CONAN_CPU_COUNT=$(nproc --all)
                  mkdir build \
                  && cd build \
                  && conan install ../source/service --profile=/conan.armv8.profile  --build missing \
                  && cmake ../source/service -DCMAKE_INSTALL_PREFIX=../install-${BB_NAME}-${ARCH} -DCMAKE_CXX_FLAGS=-I\ ../s3-gitversion/gitversion/cpp -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++\
                  && make -j${CONAN_CPU_COUNT} install
            params:
              BB_NAME: ((bb_name))
              ARCH: aarch64
              BUILD_TYPE: Release
      - task: analyze
        image: image-((bb_name))-builder
        config:
          platform: linux
          inputs:
            - name: analyze
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd analyze \
                && CodeChecker analyze compile_commands.json -o reports/ \
                && CodeChecker store reports/ --name "${BB_NAME}" --url ${CODECHECKER_URL}
            params:
              BB_NAME: ((bb_name))
              CODECHECKER_URL: ((codechecker_url))
